version: '3'
services:
  user-management:
    build:
      context: ./user-management
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - postgres-db
  product-catalog:
    build:
      context: ./product-catalog
      dockerfile: Dockerfile
    ports:
      - "8091:3000"
  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8092:5000"

  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5431:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
